
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: demo-order-service
          uri: lb://DEMO-ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: demo-user-service
          uri: lb://DEMO-USER-SERVICE
          predicates:
            - Path=/users/**

